-- Migration Script: Align Database with Collections Manifest Numbering System
-- Run this in your Supabase SQL editor to migrate from old numbering to manifest-based numbering
-- Generated by Claude Code for Story Map Project

-- ============================================================================
-- PART 1: Add collection_index field if it doesn't exist
-- ============================================================================

-- Add collection_index column to track manifest collection numbers
ALTER TABLE story_collections 
ADD COLUMN IF NOT EXISTS collection_index INTEGER;

-- ============================================================================
-- PART 2: Update collections with manifest-based numbering
-- ============================================================================

-- Update collection data based on collections-manifest.json
-- Collections are numbered 1-61 in ASCENDING chronological order (1=earliest, 61=latest)

-- Phase 1: Pre-Expedition Adventures (Collections 1-8)
UPDATE story_collections SET 
  collection_index = 1,
  name = 'LADAKH 1',
  expedition_phase = 'pre_expedition',
  estimated_date = '2022-06-01'
WHERE highlight_id = '18064808941402631:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 2,
  name = 'LADAKH 2',
  expedition_phase = 'pre_expedition',
  estimated_date = '2022-06-15'
WHERE highlight_id = '17984999519177523:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 3,
  name = 'NEW DELHI',
  expedition_phase = 'pre_expedition',
  estimated_date = '2022-07-01'
WHERE highlight_id = '17909494379698894:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 4,
  name = 'INDONESIA',
  expedition_phase = 'pre_expedition',
  estimated_date = '2022-08-01'
WHERE highlight_id = '18001194349870466:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 5,
  name = '下関 - 津山 🚴 上集',
  expedition_phase = 'pre_expedition',
  estimated_date = '2022-09-01'
WHERE highlight_id = '17893662158920583:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 6,
  name = '下関 - 津山 🚴 中集',
  expedition_phase = 'pre_expedition',
  estimated_date = '2022-09-15'
WHERE highlight_id = '17847537087090006:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 7,
  name = '下関 - 津山 🚴 下集',
  expedition_phase = 'pre_expedition',
  estimated_date = '2022-10-01'
WHERE highlight_id = '18048074443469949:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 8,
  name = '日光',
  expedition_phase = 'pre_expedition',
  estimated_date = '2022-10-15'
WHERE highlight_id = '18202733329277692:breakingcycles.life';

-- Phase 2: North China & Mongolia (Collections 9-11)
UPDATE story_collections SET 
  collection_index = 9,
  name = 'MONGOLIA WINTER',
  expedition_phase = 'north_china',
  estimated_date = '2024-02-24'
WHERE highlight_id = '17958474221619709:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 10,
  name = 'Mongolia 🇲🇳',
  expedition_phase = 'north_china',
  estimated_date = '2024-06-29'
WHERE highlight_id = '17977584701709245:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 11,
  name = 'Q&A',
  expedition_phase = 'north_china',
  estimated_date = '2024-07-20'
WHERE highlight_id = '18447928921046336:breakingcycles.life';

-- Phase 3: Central Asia (Collections 12-21)
UPDATE story_collections SET 
  collection_index = 12,
  name = 'Kyrgyzstan 🇰🇬',
  expedition_phase = 'central_asia',
  estimated_date = '2024-07-23'
WHERE highlight_id = '18450623119021935:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 13,
  name = 'Kazakhstan 🇰🇿 1',
  expedition_phase = 'central_asia',
  estimated_date = '2024-07-19'
WHERE highlight_id = '18008045279547582:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 14,
  name = 'Kazakhstan 🇰🇿 2',
  expedition_phase = 'central_asia',
  estimated_date = '2024-08-20'
WHERE highlight_id = '18058314775659069:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 15,
  name = 'Uzbekistan 🇺🇿 1',
  expedition_phase = 'central_asia',
  estimated_date = '2024-08-08'
WHERE highlight_id = '18122776447372808:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 16,
  name = 'Uzbekistan 🇺🇿 2',
  expedition_phase = 'central_asia',
  estimated_date = '2024-09-10'
WHERE highlight_id = '18075540595554032:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 17,
  name = 'Uzbekistan 🇺🇿 3',
  expedition_phase = 'central_asia',
  estimated_date = '2024-09-17'
WHERE highlight_id = '17952841943822134:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 18,
  name = 'Kazakhstan 🇰🇿 3',
  expedition_phase = 'central_asia',
  estimated_date = '2024-08-31'
WHERE highlight_id = '18053779645660840:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 19,
  name = 'Kazakhstan 🇰🇿 4',
  expedition_phase = 'central_asia',
  estimated_date = '2024-09-25'
WHERE highlight_id = '18103024393441878:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 20,
  name = 'Russia 🇷🇺',
  expedition_phase = 'central_asia',
  estimated_date = '2024-07-18'
WHERE highlight_id = '17965710818773208:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 21,
  name = 'Tajikistan 🇹🇯',
  expedition_phase = 'central_asia',
  estimated_date = '2024-07-29'
WHERE highlight_id = '18040006774818828:breakingcycles.life';

-- Phase 4: Middle East & Caucasus (Collections 22-30)
UPDATE story_collections SET 
  collection_index = 22,
  name = 'Georgia 🇬🇪 1',
  expedition_phase = 'middle_east_caucasus',
  estimated_date = '2024-10-06'
WHERE highlight_id = '17858220288266313:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 23,
  name = 'Georgia 🇬🇪 2',
  expedition_phase = 'middle_east_caucasus',
  estimated_date = '2024-10-11'
WHERE highlight_id = '18011275097400978:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 24,
  name = 'Armenia 🇦🇲 1',
  expedition_phase = 'middle_east_caucasus',
  estimated_date = '2024-10-21'
WHERE highlight_id = '18137731558325083:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 25,
  name = 'Armenia 🇦🇲2',
  expedition_phase = 'middle_east_caucasus',
  estimated_date = '2024-10-24'
WHERE highlight_id = '18044368168879405:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 26,
  name = 'Armenia 🇦🇲 3',
  expedition_phase = 'middle_east_caucasus',
  estimated_date = '2024-10-30'
WHERE highlight_id = '18040879571160857:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 27,
  name = 'Georgia 🇬🇪 3',
  expedition_phase = 'middle_east_caucasus',
  estimated_date = '2024-11-03'
WHERE highlight_id = '17932289318951599:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 28,
  name = 'Turkey 🇹🇷 1',
  expedition_phase = 'middle_east_caucasus',
  estimated_date = '2024-11-09'
WHERE highlight_id = '18066993982649869:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 29,
  name = 'Turkey 🇹🇷 2',
  expedition_phase = 'middle_east_caucasus',
  estimated_date = '2024-11-18'
WHERE highlight_id = '18037664711047569:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 30,
  name = 'Turkey 🇹🇷 3',
  expedition_phase = 'middle_east_caucasus',
  estimated_date = '2024-11-27'
WHERE highlight_id = '17987636276756920:breakingcycles.life';

-- Phase 5: Europe Part 1 (Collections 31-41)
UPDATE story_collections SET 
  collection_index = 31,
  name = 'Bulgaria 🇧🇬',
  expedition_phase = 'europe_part1',
  estimated_date = '2024-12-06'
WHERE highlight_id = '18052837759821656:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 32,
  name = 'Greece 🇬🇷 I',
  expedition_phase = 'europe_part1',
  estimated_date = '2024-12-10'
WHERE highlight_id = '17991220025742686:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 33,
  name = 'Greece 🇬🇷 II',
  expedition_phase = 'europe_part1',
  estimated_date = '2024-12-19'
WHERE highlight_id = '18044152921980963:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 34,
  name = 'Souls pt. 1',
  expedition_phase = 'europe_part1',
  estimated_date = '2024-07-11'
WHERE highlight_id = '17916693795030579:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 35,
  name = 'Italy 🇮🇹 I',
  expedition_phase = 'europe_part1',
  estimated_date = '2024-12-27'
WHERE highlight_id = '17889230265118966:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 36,
  name = 'Italy 🇮🇹 II',
  expedition_phase = 'europe_part1',
  estimated_date = '2025-01-09'
WHERE highlight_id = '18102396352485795:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 37,
  name = 'MFW2025 Vol I',
  expedition_phase = 'europe_part1',
  estimated_date = '2025-01-18'
WHERE highlight_id = '18347481994183019:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 38,
  name = 'MFW2025 Vol II',
  expedition_phase = 'europe_part1',
  estimated_date = '2025-01-20'
WHERE highlight_id = '17991384335769961:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 39,
  name = 'France 🇫🇷',
  expedition_phase = 'europe_part1',
  estimated_date = '2025-01-23'
WHERE highlight_id = '18038123462528317:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 40,
  name = 'Spain 🇪🇸 I',
  expedition_phase = 'europe_part1',
  estimated_date = '2025-01-25'
WHERE highlight_id = '18071829082750153:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 41,
  name = 'Spain 🇪🇸 II',
  expedition_phase = 'europe_part1',
  estimated_date = '2025-02-07'
WHERE highlight_id = '18035501075407752:breakingcycles.life';

-- Phase 6: Africa (Collections 42-50)
UPDATE story_collections SET 
  collection_index = 42,
  name = 'Italy 🇮🇹 III',
  expedition_phase = 'africa',
  estimated_date = '2025-01-17'
WHERE highlight_id = '18048676087963901:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 43,
  name = 'Morocco 🇲🇦 I',
  expedition_phase = 'africa',
  estimated_date = '2025-02-01'
WHERE highlight_id = '18079492300619829:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 44,
  name = 'Thoughts',
  expedition_phase = 'africa',
  estimated_date = '2024-08-08'
WHERE highlight_id = '18030793766230793:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 45,
  name = 'Morocco 🇲🇦 II',
  expedition_phase = 'africa',
  estimated_date = '2025-02-10'
WHERE highlight_id = '18077175703725858:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 46,
  name = 'Morocco 🇲🇦 III',
  expedition_phase = 'africa',
  estimated_date = '2025-02-18'
WHERE highlight_id = '17908767675094414:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 47,
  name = 'Morocco 🇲🇦 IV',
  expedition_phase = 'africa',
  estimated_date = '2025-03-03'
WHERE highlight_id = '17949446570943474:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 48,
  name = 'Souls pt. 2',
  expedition_phase = 'africa',
  estimated_date = '2024-12-30'
WHERE highlight_id = '17975341163805031:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 49,
  name = 'Morocco 🇲🇦 V',
  expedition_phase = 'africa',
  estimated_date = '2025-03-20'
WHERE highlight_id = '17932045244897253:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 50,
  name = 'Morocco 🇲🇦 VI',
  expedition_phase = 'africa',
  estimated_date = '2025-04-06'
WHERE highlight_id = '17973374066841093:breakingcycles.life';

-- Phase 7: Europe Part 2 & UK/Scotland (Collections 51-61)
UPDATE story_collections SET 
  collection_index = 51,
  name = 'Germany 🇩🇪 I',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-04-24'
WHERE highlight_id = '17935663073901419:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 52,
  name = 'Germany 🇩🇪 II',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-05-12'
WHERE highlight_id = '18500727481005649:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 53,
  name = 'England - Part 1 🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-05-25'
WHERE highlight_id = '18017304146710500:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 54,
  name = 'Build 2.0',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-04-28'
WHERE highlight_id = '18057215815963683:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 55,
  name = 'England - Part 2 🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-06-08'
WHERE highlight_id = '18089901049624656:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 56,
  name = 'England - Part 3 🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-06-21'
WHERE highlight_id = '18070381891972059:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 57,
  name = 'Podcast',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-07-12'
WHERE highlight_id = '18062166557266367:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 58,
  name = 'Scotland - Part 1 🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-07-12'
WHERE highlight_id = '18070600946491546:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 59,
  name = 'Wales 🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-07-31'
WHERE highlight_id = '18011241530716717:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 60,
  name = 'Scotland - Part 2 🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-07-24'
WHERE highlight_id = '18077415214744071:breakingcycles.life';

UPDATE story_collections SET 
  collection_index = 61,
  name = 'England - Part 4 🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  expedition_phase = 'europe_uk_scotland',
  estimated_date = '2025-07-09'
WHERE highlight_id = '18068925452490325:breakingcycles.life';

-- ============================================================================
-- PART 3: Add expedition scope tracking
-- ============================================================================

-- Add expedition scope fields if they don't exist
ALTER TABLE story_collections 
ADD COLUMN IF NOT EXISTS is_expedition_scope BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS expedition_exclude_reason TEXT;

-- Mark pre-expedition collections (Collections 1-8) as excluded from expedition scope
UPDATE story_collections 
SET 
  is_expedition_scope = false,
  expedition_exclude_reason = 'pre_expedition_content'
WHERE collection_index BETWEEN 1 AND 8;

-- Mark expedition content (Collections 9-61) as included in expedition scope
UPDATE story_collections 
SET 
  is_expedition_scope = true,
  expedition_exclude_reason = NULL
WHERE collection_index BETWEEN 9 AND 61;

-- ============================================================================
-- PART 4: Create indexes for new collection_index field
-- ============================================================================

-- Add unique constraint and index for collection_index
ALTER TABLE story_collections ADD CONSTRAINT uk_collection_index UNIQUE (collection_index);
CREATE INDEX IF NOT EXISTS idx_collection_index ON story_collections(collection_index);
CREATE INDEX IF NOT EXISTS idx_expedition_scope ON story_collections(is_expedition_scope);

-- ============================================================================
-- PART 5: Verification queries
-- ============================================================================

-- Verify collection numbering and expedition phases
SELECT 
  collection_index,
  name,
  expedition_phase,
  estimated_date,
  is_expedition_scope,
  expedition_exclude_reason
FROM story_collections 
WHERE collection_index IS NOT NULL
ORDER BY collection_index;

-- Count collections by expedition phase
SELECT 
  expedition_phase,
  COUNT(*) as collection_count,
  MIN(collection_index) as first_collection,
  MAX(collection_index) as last_collection,
  COUNT(CASE WHEN is_expedition_scope = true THEN 1 END) as expedition_collections,
  COUNT(CASE WHEN is_expedition_scope = false THEN 1 END) as excluded_collections
FROM story_collections 
WHERE collection_index IS NOT NULL
GROUP BY expedition_phase
ORDER BY MIN(collection_index);

-- Verify chronological ordering (should be ascending by date)
SELECT 
  collection_index,
  name,
  estimated_date,
  LAG(estimated_date) OVER (ORDER BY collection_index) as previous_date,
  CASE 
    WHEN estimated_date >= LAG(estimated_date) OVER (ORDER BY collection_index) OR LAG(estimated_date) OVER (ORDER BY collection_index) IS NULL THEN 'CORRECT'
    ELSE 'DATE_ORDER_ERROR'
  END as chronological_check
FROM story_collections 
WHERE collection_index IS NOT NULL
ORDER BY collection_index;

-- ============================================================================
-- NOTES FOR IMPLEMENTATION
-- ============================================================================

/*
MIGRATION SUMMARY:

1. COLLECTION NUMBERING: Now uses ascending chronological order (1=earliest, 61=latest)
   - Collection 1: LADAKH 1 (earliest, 2022-06-01)
   - Collection 61: England - Part 4 (latest, 2025-07-09)

2. EXPEDITION SCOPE TRACKING:
   - Collections 1-8: Pre-expedition content (excluded from GPS correlation)
   - Collections 9-61: Expedition content (included in GPS correlation)

3. EXPEDITION PHASES (7 phases):
   - pre_expedition (1-8): 2022-2023
   - north_china (9-11): June-July 2024
   - central_asia (12-21): July-September 2024
   - middle_east_caucasus (22-30): October-November 2024
   - europe_part1 (31-41): December 2024-February 2025
   - africa (42-50): February-April 2025
   - europe_uk_scotland (51-61): April-July 2025

4. CRITICAL CHANGES:
   - OLD: Collections in DESCENDING order (1=latest, 61=earliest)
   - NEW: Collections in ASCENDING order (1=earliest, 61=latest)
   - All TypeScript interfaces and components need updating
   - GPS correlation logic needs updating
   - Frontend display order needs updating

5. NEXT STEPS:
   - Update TypeScript interfaces to reflect new numbering
   - Update components to use ascending order
   - Update GPS correlation services
   - Remove old collection number references from codebase
*/